[package]
name = "cf-qemu-post"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
regex = "1.11.1"

[[bin]]
name="tracegen"
path="src/main.rs"

[[bin]]
name="logmerge"
path="src/log_merger.rs"
